---
- name: Install Collectd
  package:
    name: collectd
    state: present

- name: Ensure Collectd service is started and enabled
  service:
    name: collectd
    state: started
    enabled: yes

- name: Configure Collectd
  template:
    src: collectd.conf.j2
    dest: /etc/collectd.d/prometheus.conf
  notify: restart collectd
