---
- name: Detener y eliminar Collectd
  service:
    name: collectd
    state: stopped
  ignore_errors: yes

- name: Eliminar paquete Collectd
  package:
    name: collectd
    state: absent

- name: Eliminar configuración de Collectd
  file:
    path: /etc/collectd.d/prometheus.conf
    state: absent