# Archivo: remove_collectd_playbook.yml

- name: Remove collectd and clean up
  hosts: all
  become: yes  # Usa permisos de superusuario si es necesario
  tasks:
    - name: Stop collectd service
      service:
        name: collectd
        state: stopped

    - name: Remove collectd service
      systemd:
        name: collectd
        state: absent

    - name: Remove collectd package
      package:
        name: collectd
        state: absent

    - name: Remove collectd plugins
      package:
        name: collectd-plugins
        state: absent

    - name: Remove collectd configuration files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/collectd/collectd.conf
        - /etc/collectd/collectd.conf.d/
        - /etc/collectd.d/
